from fpdf import FPDF
from datetime import datetime

class SitRepPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Situation Report (SitRep) - Disaster Guard AI', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_sitrep(region, risk_level, likelihood, impact, threat_type, population, recommendations):
    pdf = SitRepPDF()
    pdf.add_page()
    
    # 1. Overview
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"Region: {region}", 0, 1)
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 10, f"Date/Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1)
    pdf.ln(5)
    
    # 2. Risk Status
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Risk Assessment", 0, 1)
    
    # Color coding simulation (Text based)
    risk_desc = f"RISK LEVEL: {risk_level.upper()}"
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(255, 0, 0) if risk_level == 'High' else pdf.set_text_color(255, 165, 0) if risk_level == 'Moderate' else pdf.set_text_color(0, 128, 0)
    pdf.cell(0, 10, risk_desc, 0, 1)
    pdf.set_text_color(0, 0, 0) # Reset
    
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 8, f"Primary Threat: {threat_type}", 0, 1)
    pdf.cell(0, 8, f"Likelihood: {likelihood*100:.1f}%", 0, 1)
    pdf.cell(0, 8, f"Impact/Vulnerability Score: {impact*100:.1f}%", 0, 1)
    pdf.cell(0, 8, f"Est. Population at Risk: {int(population):,}", 0, 1)
    pdf.ln(5)
    
    # 3. Actions
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Recommended Actions", 0, 1)
    pdf.set_font("Arial", '', 10)
    for rec in recommendations:
        pdf.cell(0, 8, f"- {rec}", 0, 1)
    
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "This report is auto-generated by AI. Verify with official sources (IMD/NDMA) for operational use.", 0, 1)
    
    return pdf.output(dest='S').encode('latin-1') 
